"""Added tax triage chronic conditions and nursing notes

Revision ID: 048b33f48cd0
Revises: 
Create Date: 2026-02-18 14:57:58.780773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048b33f48cd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_suggestions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('ai_suggestions')

    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('tax_percentage')

    # ### end Alembic commands ###
