"""remove unique constraint from user name

Revision ID: 59be476927ef
Revises: 048b33f48cd0
Create Date: 2026-02-18 16:22:35.767423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59be476927ef'
down_revision = '048b33f48cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
